[project]
name = "inlp-project"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "matplotlib",
    "tqdm",
    "pyarrow",
    "torch",
    "transformers",
    "sentence-transformers",
    "requests",
    "python-dotenv",
    "tiktoken",
    "datasets",
]

[tool.uv]
dev-dependencies = []
